package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private int idCalificacion;
     private String descripcion;
     private String color;
     private int valor;
     private Set evaluacionSeguridads = new HashSet(0);

    public Calificacion() {
    }

	
    public Calificacion(int idCalificacion, String descripcion, String color, int valor) {
        this.idCalificacion = idCalificacion;
        this.descripcion = descripcion;
        this.color = color;
        this.valor = valor;
    }
    public Calificacion(int idCalificacion, String descripcion, String color, int valor, Set evaluacionSeguridads) {
       this.idCalificacion = idCalificacion;
       this.descripcion = descripcion;
       this.color = color;
       this.valor = valor;
       this.evaluacionSeguridads = evaluacionSeguridads;
    }
   
    public int getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set getEvaluacionSeguridads() {
        return this.evaluacionSeguridads;
    }
    
    public void setEvaluacionSeguridads(Set evaluacionSeguridads) {
        this.evaluacionSeguridads = evaluacionSeguridads;
    }




}


