package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Colonia generated by hbm2java
 */
public class Colonia  implements java.io.Serializable {


     private Integer idColonia;
     private String descripcion;
     private Set evaluacionServicios = new HashSet(0);

    public Colonia() {
    }

	
    public Colonia(String descripcion) {
        this.descripcion = descripcion;
    }
    public Colonia(String descripcion, Set evaluacionServicios) {
       this.descripcion = descripcion;
       this.evaluacionServicios = evaluacionServicios;
    }
   
    public Integer getIdColonia() {
        return this.idColonia;
    }
    
    public void setIdColonia(Integer idColonia) {
        this.idColonia = idColonia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEvaluacionServicios() {
        return this.evaluacionServicios;
    }
    
    public void setEvaluacionServicios(Set evaluacionServicios) {
        this.evaluacionServicios = evaluacionServicios;
    }




}


