package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Delegacion generated by hbm2java
 */
public class Delegacion  implements java.io.Serializable {


     private Integer idDelegacion;
     private String descripcion;
     private Set evaluacionServicios = new HashSet(0);

    public Delegacion() {
    }

	
    public Delegacion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Delegacion(String descripcion, Set evaluacionServicios) {
       this.descripcion = descripcion;
       this.evaluacionServicios = evaluacionServicios;
    }
   
    public Integer getIdDelegacion() {
        return this.idDelegacion;
    }
    
    public void setIdDelegacion(Integer idDelegacion) {
        this.idDelegacion = idDelegacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEvaluacionServicios() {
        return this.evaluacionServicios;
    }
    
    public void setEvaluacionServicios(Set evaluacionServicios) {
        this.evaluacionServicios = evaluacionServicios;
    }




}


