package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EvaluacionServicio generated by hbm2java
 */
public class EvaluacionServicio  implements java.io.Serializable {


     private Integer idEvaluacionServicio;
     private Calle calle;
     private Colonia colonia;
     private Delegacion delegacion;
     private ServicioPublico servicioPublico;
     private Usuario usuario;
     private Date tsCreacion;
     private BigDecimal localizacionN;
     private BigDecimal localizacionW;
     private String comentario;
     private String urlFoto;
     private int noPoste;

    public EvaluacionServicio() {
    }

    public EvaluacionServicio(Calle calle, Colonia colonia, Delegacion delegacion, ServicioPublico servicioPublico, Usuario usuario, Date tsCreacion, BigDecimal localizacionN, BigDecimal localizacionW, String comentario, String urlFoto, int noPoste) {
       this.calle = calle;
       this.colonia = colonia;
       this.delegacion = delegacion;
       this.servicioPublico = servicioPublico;
       this.usuario = usuario;
       this.tsCreacion = tsCreacion;
       this.localizacionN = localizacionN;
       this.localizacionW = localizacionW;
       this.comentario = comentario;
       this.urlFoto = urlFoto;
       this.noPoste = noPoste;
    }
   
    public Integer getIdEvaluacionServicio() {
        return this.idEvaluacionServicio;
    }
    
    public void setIdEvaluacionServicio(Integer idEvaluacionServicio) {
        this.idEvaluacionServicio = idEvaluacionServicio;
    }
    public Calle getCalle() {
        return this.calle;
    }
    
    public void setCalle(Calle calle) {
        this.calle = calle;
    }
    public Colonia getColonia() {
        return this.colonia;
    }
    
    public void setColonia(Colonia colonia) {
        this.colonia = colonia;
    }
    public Delegacion getDelegacion() {
        return this.delegacion;
    }
    
    public void setDelegacion(Delegacion delegacion) {
        this.delegacion = delegacion;
    }
    public ServicioPublico getServicioPublico() {
        return this.servicioPublico;
    }
    
    public void setServicioPublico(ServicioPublico servicioPublico) {
        this.servicioPublico = servicioPublico;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getTsCreacion() {
        return this.tsCreacion;
    }
    
    public void setTsCreacion(Date tsCreacion) {
        this.tsCreacion = tsCreacion;
    }
    public BigDecimal getLocalizacionN() {
        return this.localizacionN;
    }
    
    public void setLocalizacionN(BigDecimal localizacionN) {
        this.localizacionN = localizacionN;
    }
    public BigDecimal getLocalizacionW() {
        return this.localizacionW;
    }
    
    public void setLocalizacionW(BigDecimal localizacionW) {
        this.localizacionW = localizacionW;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getUrlFoto() {
        return this.urlFoto;
    }
    
    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }
    public int getNoPoste() {
        return this.noPoste;
    }
    
    public void setNoPoste(int noPoste) {
        this.noPoste = noPoste;
    }




}


