package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EvaluacionSeguridad generated by hbm2java
 */
public class EvaluacionSeguridad  implements java.io.Serializable {


     private Integer idEvaluacionSeguridad;
     private Calificacion calificacion;
     private Calle calle;
     private Usuario usuario;
     private Date tsCreacion;
     private BigDecimal primeraLocalizacionN;
     private BigDecimal primeraLocalizacionW;
     private BigDecimal segundaLocalizacionN;
     private BigDecimal segundaLocalizacionW;
     private Set motivos = new HashSet(0);
     private Set incidentes = new HashSet(0);

    public EvaluacionSeguridad() {
    }

	
    public EvaluacionSeguridad(Calificacion calificacion, Calle calle, Usuario usuario, Date tsCreacion, BigDecimal primeraLocalizacionN, BigDecimal primeraLocalizacionW, BigDecimal segundaLocalizacionN, BigDecimal segundaLocalizacionW) {
        this.calificacion = calificacion;
        this.calle = calle;
        this.usuario = usuario;
        this.tsCreacion = tsCreacion;
        this.primeraLocalizacionN = primeraLocalizacionN;
        this.primeraLocalizacionW = primeraLocalizacionW;
        this.segundaLocalizacionN = segundaLocalizacionN;
        this.segundaLocalizacionW = segundaLocalizacionW;
    }
    public EvaluacionSeguridad(Calificacion calificacion, Calle calle, Usuario usuario, Date tsCreacion, BigDecimal primeraLocalizacionN, BigDecimal primeraLocalizacionW, BigDecimal segundaLocalizacionN, BigDecimal segundaLocalizacionW, Set motivos, Set incidentes) {
       this.calificacion = calificacion;
       this.calle = calle;
       this.usuario = usuario;
       this.tsCreacion = tsCreacion;
       this.primeraLocalizacionN = primeraLocalizacionN;
       this.primeraLocalizacionW = primeraLocalizacionW;
       this.segundaLocalizacionN = segundaLocalizacionN;
       this.segundaLocalizacionW = segundaLocalizacionW;
       this.motivos = motivos;
       this.incidentes = incidentes;
    }
   
    public Integer getIdEvaluacionSeguridad() {
        return this.idEvaluacionSeguridad;
    }
    
    public void setIdEvaluacionSeguridad(Integer idEvaluacionSeguridad) {
        this.idEvaluacionSeguridad = idEvaluacionSeguridad;
    }
    public Calificacion getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Calificacion calificacion) {
        this.calificacion = calificacion;
    }
    public Calle getCalle() {
        return this.calle;
    }
    
    public void setCalle(Calle calle) {
        this.calle = calle;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getTsCreacion() {
        return this.tsCreacion;
    }
    
    public void setTsCreacion(Date tsCreacion) {
        this.tsCreacion = tsCreacion;
    }
    public BigDecimal getPrimeraLocalizacionN() {
        return this.primeraLocalizacionN;
    }
    
    public void setPrimeraLocalizacionN(BigDecimal primeraLocalizacionN) {
        this.primeraLocalizacionN = primeraLocalizacionN;
    }
    public BigDecimal getPrimeraLocalizacionW() {
        return this.primeraLocalizacionW;
    }
    
    public void setPrimeraLocalizacionW(BigDecimal primeraLocalizacionW) {
        this.primeraLocalizacionW = primeraLocalizacionW;
    }
    public BigDecimal getSegundaLocalizacionN() {
        return this.segundaLocalizacionN;
    }
    
    public void setSegundaLocalizacionN(BigDecimal segundaLocalizacionN) {
        this.segundaLocalizacionN = segundaLocalizacionN;
    }
    public BigDecimal getSegundaLocalizacionW() {
        return this.segundaLocalizacionW;
    }
    
    public void setSegundaLocalizacionW(BigDecimal segundaLocalizacionW) {
        this.segundaLocalizacionW = segundaLocalizacionW;
    }
    public Set getMotivos() {
        return this.motivos;
    }
    
    public void setMotivos(Set motivos) {
        this.motivos = motivos;
    }
    public Set getIncidentes() {
        return this.incidentes;
    }
    
    public void setIncidentes(Set incidentes) {
        this.incidentes = incidentes;
    }




}


