package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Incidente generated by hbm2java
 */
public class Incidente  implements java.io.Serializable {


     private int idIncidente;
     private String descripcion;
     private Set evaluacionSeguridads = new HashSet(0);

    public Incidente() {
    }

	
    public Incidente(int idIncidente, String descripcion) {
        this.idIncidente = idIncidente;
        this.descripcion = descripcion;
    }
    public Incidente(int idIncidente, String descripcion, Set evaluacionSeguridads) {
       this.idIncidente = idIncidente;
       this.descripcion = descripcion;
       this.evaluacionSeguridads = evaluacionSeguridads;
    }
   
    public int getIdIncidente() {
        return this.idIncidente;
    }
    
    public void setIdIncidente(int idIncidente) {
        this.idIncidente = idIncidente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEvaluacionSeguridads() {
        return this.evaluacionSeguridads;
    }
    
    public void setEvaluacionSeguridads(Set evaluacionSeguridads) {
        this.evaluacionSeguridads = evaluacionSeguridads;
    }




}


