package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Motivo generated by hbm2java
 */
public class Motivo  implements java.io.Serializable {


     private int idMotivo;
     private String descripcion;
     private Set evaluacionSeguridads = new HashSet(0);

    public Motivo() {
    }

	
    public Motivo(int idMotivo, String descripcion) {
        this.idMotivo = idMotivo;
        this.descripcion = descripcion;
    }
    public Motivo(int idMotivo, String descripcion, Set evaluacionSeguridads) {
       this.idMotivo = idMotivo;
       this.descripcion = descripcion;
       this.evaluacionSeguridads = evaluacionSeguridads;
    }
   
    public int getIdMotivo() {
        return this.idMotivo;
    }
    
    public void setIdMotivo(int idMotivo) {
        this.idMotivo = idMotivo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEvaluacionSeguridads() {
        return this.evaluacionSeguridads;
    }
    
    public void setEvaluacionSeguridads(Set evaluacionSeguridads) {
        this.evaluacionSeguridads = evaluacionSeguridads;
    }




}


