package com.bajaintec.entities;
// Generated Mar 12, 2016 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token  implements java.io.Serializable {


     private String idToken;
     private Usuario usuario;
     private Date tsCreacion;

    public Token() {
    }

    public Token(String idToken, Usuario usuario, Date tsCreacion) {
       this.idToken = idToken;
       this.usuario = usuario;
       this.tsCreacion = tsCreacion;
    }
   
    public String getIdToken() {
        return this.idToken;
    }
    
    public void setIdToken(String idToken) {
        this.idToken = idToken;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getTsCreacion() {
        return this.tsCreacion;
    }
    
    public void setTsCreacion(Date tsCreacion) {
        this.tsCreacion = tsCreacion;
    }




}


